Fix broken pip install line continuation in Dockerfile
Removes the trailing \ after the pip install command.

The previous line continuation caused WORKDIR /root/ to be appended to the install command, resulting in:

ERROR: Directory '/root/' is not installable